### PR TITLE
update hideCursor readme to include SIGINT info

### PR DESCRIPTION
**Pull request by Thomazella**
Please let me know if you have any feedback.

### CODE REVIEW

**Comment by sindresorhus** [comment]
What's the context?

**Comment by diegohaz** [comment]
@sindresorhus We were using `meow` and `ora` on https://github.com/diegohaz/singel and having problems to stop logging stuff on SIGINT.

It took us a long time to figure out what was blocking the process, and turned out that both `ora` and `meow` were responsible for that. We replaced `meow` by `commander` and added the `hideCursor` option to `ora` and everything was fixed. (here: https://github.com/diegohaz/singel/pull/17)

That would be easier if the readme said something about that.

**Comment by sindresorhus** [comment]
Sounds like https://github.com/tapjs/signal-exit/issues/49

**Comment by diegohaz** [comment]
Didn't get it. What does that package have to do with `ora` or `hideCursor`?

**Comment by sindresorhus** [comment]
Closing in favor of https://github.com/tapjs/signal-exit/issues/49.

**Review by ubsasi — COMMENTED** [review]
Yy

**Pull request closed without merging**
