### PR TITLE
Hide `prefixText` when it's an empty string

### LINKED ISSUE #122: Undesirable space before spinner symbol when prefixText is empty string
I set `prefixText` like this:

```js
spinner.prefixText = 'Loading';
spinner.spinner = 'simpleDots';
spinner.start();
...
spinner.stop();
```

Then, I set `prefixText` to an empty string and reuse the `spinner`:

```js
spinner.prefixText = '';
spinner.spinner = 'dots';
spinner.start();
```

This time, before the spinner symbol, there's one undesirable space.

The cause is this code in the `frame` method (https://github.com/sindresorhus/ora/blob/master/index.js#L119):

```
const fullPrefixText = typeof this.prefixText === 'string' ? this.prefixText + ' ' : '';
```

Initially, `prefixText` is `undefined` so the code worked. But after it's set to an empty string, it doesn't work as expected.

I'm using TypeScript. Setting like this will cause syntax error (https://github.com/sindresorhus/ora/blob/master/index.d.ts#L127):

```js
spinner.prefixText = undefined;
```

I have to do like this (not very nice):

```ts
this.spinner.prefixText = undefined as any;
```

### PR DESCRIPTION
**Pull request by stroncium**
Fixes #122

### CODE REVIEW

**Comment by sindresorhus** [comment]
I think it would be better to fix the JS code to also accept an empty string, without adding the padding. I prefer to keep TS types as simple as possible.

**Comment by stroncium** [comment]
@sindresorhus But we will have inconsistency then.
```
'  ' => '   spinner'
' '  => '  spinner'
''   => 'spinner'
```
and no way to put just one space in.

**Comment by stroncium** [comment]
Also, as it can be `undefined` from beginning, it makes sense to me we should be able to assign `undefined` to it(I actually thought it was the case from the start, but weirdly enough, optional field can be undefined, but can't be assigned undefined).

**Comment by sindresorhus** [comment]
Good point. I missed your comment in the issue. Ignore my previous comment.

**Comment by sindresorhus** [comment]
Can you document in words that setting it to `undefined` will hide the prefix? In the readme too.

**Comment by sindresorhus** [comment]
Hmm, actually, thinking about this more, would anyone actually want an empty space before the spinner? Seems logical to me that the empty space is just a joiner, so when `prefixText` is empty, there's no space.

**Comment by sindresorhus** [comment]
> Hmm, actually, thinking about this more, would anyone actually want an empty space before the spinner? Seems logical to me that the empty space is just a joiner, so when prefixText is empty, there's no space. prefixText is not meant to create indentation, we have the indent option for that.

@stroncium ⬆️

**Comment by stroncium** [comment]
@sindresorhus Feels weird to introduce additional code so that instead of just setting something to empty string and getting predictable result he'd set it to empty string, get unpredictable result and need to set up another option in order for result to get predictable, no?

**Comment by ngocdaothanh** [comment]
One way to fix the mess is to force users (by redesigning the APIs?) to create a new instance of ora every time, instead of allowing users to reuse an existing ora instance (immutable vs mutable).

**Comment by stroncium** [comment]
@sindresorhus I wait for your final word on this.
Allowing undefined vs special case for empty string.

Pros:
 - no additional code/logic
 - consistent results with any string supplied
 - setting `undefined` mirrors behavior for not defining

Cons:
 - setting empty string may be thought by some as equal to "removing" the value, in which case the behavior might seem weird to them

**Comment by sindresorhus** [comment]
@ngocdaothanh It's not a "mess". It's just a tiny API quirk. And I don't think immutability would solve any problems in this case (I'm saying that as someone that loves immutability in other languages).

**Comment by sindresorhus** [comment]
@stroncium I'm gonna go with "special case for empty string". Thinking about it more, it doesn't look like a special-case to me, but more like expected behavior. As long as we document it it, there should be no problems with this.

Can you also give the PR a descriptive title?

**Comment by stroncium** [comment]
@sindresorhus changed to handle empty string

**Pull request merged**
