### PR TITLE
Add `indent` option

### LINKED ISSUE #23: Add `indent` option
It would be nice to be able to control what is set to cursorTo in order to support indentation of rows, if desired.

### PR DESCRIPTION
**Pull request by yaodingyd**
Fix #23

One more try!

### CODE REVIEW

**Comment by sindresorhus** [comment]
Can you also allow changing the `indent` while Ora is running? Similar to how it's done in https://github.com/sindresorhus/ora/pull/95. Just add a public getter/setter and also validate that `indent` is an integer from 0 and up.

**Comment by sindresorhus** [comment]
Can you also document the `indent` property?

**Comment by yaodingyd** [comment]
What other documentation is needed? I already added it in the README. So I need to expand on that?

**Comment by sindresorhus** [comment]
Right now it's documented as an option, but it needs to be documented as a property too. Here: https://github.com/sindresorhus/ora#color-1

**Comment by sindresorhus** [comment]
Looks good :)

**Comment by sindresorhus** [comment]
You need to submit the PR URL to IssueHunt to claim the bounty. You can do this already when you open the PR. You don't have to wait until it's merged ;)

**Pull request merged**
