### PR TITLE
Use animated SVG demo

### PR DESCRIPTION
**Pull request by marionebl**
* Reduces file size from 184KB to 20KB 
* Better quality
---
* Generated via svg-term [svg-term-cli](https://github.com/marionebl/svg-term-cli)
* Reproduce via `cat screenshot.json | svg-term --out screenshot.svg --from=1305 --to=5300 --frame`

### CODE REVIEW

**Comment by sindresorhus** [comment]
Oh wow. `svg-term` is super awesome!! I've been wanting something like this for years!

**Comment by sindresorhus** [comment]
Is it possible to record directly to `svg-term`? I want to make it a npm run script, and then I don't need to store the JSON file.

I tried `asciinema rec --command=\"node example.js\" | svg-term --out=screenshot.svg`, but asciinema prompt for uploading which makes it not work.

**Comment by sindresorhus** [comment]
And can you submit `svg-term-cli` to https://github.com/sindresorhus/awesome-nodejs ?

**Comment by marionebl** [comment]
> Wow. svg-term is super awesome!! I've been wanting something like this for years!

Glad you like it!

> Is it possible to record directly to svg-term? I want to make it a npm run script, and then I don't need to store the JSON file.
> I tried asciinema rec --command=\"node example.js\" | svg-term --out=screenshot.svg, but asciinema prompt for uploading which makes it not work.

I used an intermediary file, too. As far as I know there currently is no way to do it directly with the `asciinema` cli as is. We could talk with @sickill about the best way to achieve this.

> And can you submit svg-term-cli to https://github.com/sindresorhus/awesome-nodejs ?

Sure. 👍

**Comment by sindresorhus** [comment]
I opened an issue: https://github.com/asciinema/asciinema/issues/255

**Pull request merged**
